# Simplified CI for GitInspectorGUI
# The actual building and deployment is handled by edu-boost.gitlab.io

stages:
    - deploy

# Trigger group pages deployment
trigger_group_pages:
    stage: deploy
    image: alpine:latest
    before_script:
        - apk add --no-cache curl
    script:
        - echo "Triggering group pages rebuild for GitInspectorGUI..."
        - |
            if curl -f -X POST \
                -F token=$DOCS_TRIGGER_TOKEN \
                -F ref=main \
                "https://gitlab.com/api/v4/projects/edu-boost%2Fedu-boost.gitlab.io/trigger/pipeline"; then
                echo "Group pages deployment triggered successfully"
                echo "Changes will be available at: https://edu-boost.gitlab.io/gitinspectorgui/"
            else
                echo "Failed to trigger deployment"
                exit 1
            fi
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
