site_name: GitInspectorGUI Documentation
site_description: Documentation for GitInspectorGUI desktop application
site_url: https://boost-edu-tools.github.io/gitinspectorgui
# Note: Updated URL after repository transfer to boost-edu-tools organization

theme:
    name: material
    palette:
        - scheme: default
          primary: blue
          accent: blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: blue
          accent: blue
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    features:
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - search.highlight
        - search.share
        - content.code.copy
        - content.action.edit
        - content.tabs.link

plugins:
    - search:
          lang: en
    - mermaid2

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - admonition
    - pymdownx.details
    - pymdownx.mark
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.tilde
    - attr_list
    - md_in_html

nav:
    - User Documentation:
          - Home: user-docs/index.md
          - Overview: user-docs/overview.md
          - Installation: user-docs/install.md
          - Quick Start: user-docs/quick-start.md
          - GUI: user-docs/gui.md
          - CLI: user-docs/cli.md
          - Output: user-docs/output.md
          - Examples: user-docs/examples.md
          - Supported: user-docs/supported.md
          - Known Issues: user-docs/known-issues.md
          - FAQ: user-docs/faq.md
          - Developer Resources: user-docs/develop.md
    - Developer Home: index.md
    - Demo: https://boost-edu-tools.github.io/gitinspectorgui/demo/
    - Technology Primer: technology-primer.md
    - Getting Started:
          - Prerequisites: getting-started/01-prerequisites.md
          - Installation: getting-started/02-installation.md
          - Quick Start: getting-started/03-quick-start.md
    - Development:
          - Environment Setup: development/environment-setup.md
          - Development Workflow: development/development-workflow.md
          - Commands Reference: development/development-commands.md
          - Package Management:
                - Overview: development/package-management-overview.md
                - Python Dependencies: development/python-package-management.md
                - JavaScript Dependencies: development/javascript-package-management.md
          - CLI Development Guide: development/cli-development-guide.md
          - Build Process: development/build-process.md
          - Publishing: development/publishing.md
          - Troubleshooting: development/troubleshooting.md
          - Advanced:
                - Demo-Based Development: development/advanced/demo-based-development.md
                - Design System Integration: development/advanced/design-system-integration.md
    - API Reference:
          - Python API Reference: api/reference.md
          - Examples: api/examples.md
          - Error Handling: api/error-handling.md
    - Architecture:
          - Design Background: architecture/design-background-info.md
          - System Overview: architecture/overview.md
          - Technology Stack: architecture/technology-stack.md
          - Design Decisions: architecture/design-decisions.md
          - Legacy Integration: architecture/legacy-integration.md
    - Operations:
          - Release & Distribution: operations/deployment.md
          - Server Management: operations/server-management.md
          - Maintenance: operations/maintenance.md
          - Documentation Deployment: operations/documentation-deployment.md

repo_url: https://github.com/boost-edu-tools/gitinspectorgui
edit_uri: edit/main/docs/

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/boost-edu-tools/gitinspectorgui
