site_name: GitInspectorGUI Developer Documentation
site_description: Developer documentation for GitInspectorGUI desktop application
site_url: https://edu-boost.gitlab.io/gitinspectorgui
# Note: Update URLs above when forking/moving this project

theme:
    name: material
    palette:
        - scheme: default
          primary: blue
          accent: blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: blue
          accent: blue
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    features:
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - search.highlight
        - search.share
        - content.code.copy
        - content.action.edit
        - content.tabs.link

plugins:
    - search:
          lang: en
    - mermaid2

# Exclude problematic files with broken links
exclude_docs: |
    api/HTTP_API_REFERENCE.md
    architecture/ARCHITECTURE_DIAGRAMS.md
    architecture/ARCHITECTURE_PLAN_SUMMARY.md
    archive/
    ai-tools-old/
    deployment/PRODUCTION_DEPLOYMENT_GUIDE.md
    development/API_SIDECAR.md
    development/DEVELOPMENT_MODE.md
    development/ENHANCED_SETTINGS_GUIDE.md
    implementation/
    operations/rollback/
    DOCUMENTATION_CLEANUP_PLAN.md

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - admonition
    - pymdownx.details
    - pymdownx.mark
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.tilde
    - attr_list
    - md_in_html

nav:
    - Home: index.md
    - Demo: demo/
    - Getting Started:
          - Quick Start: getting-started/quick-start.md
          - Installation: getting-started/installation.md
          - First Analysis: getting-started/first-analysis.md
    - Development:
          - Environment Setup: development/environment-setup.md
          - Development Mode: development/development-mode.md
          - Demo-Based Documentation-GUI Development: development/demo-based-documentation-gui-development.md
          - Design System Integration: development/design-system-integration.md
          - Python Package Management (uv): development/python-management-uv.md
          - Node.js Package Management (pnpm): development/package-management-pnpm.md
          - Enhanced Settings: development/enhanced-settings.md
          - Blame Tabs Implementation: development/blame-tabs-implementation.md
          - Troubleshooting: development/troubleshooting.md
    - AI Tools:
          - Overview: ai-tools/overview.md
          - Roo Code Development Guide: ai-tools/roo-code-guide.md
          - Cline Development Guide: ai-tools/cline-guide.md
    - API Reference:
          - HTTP API Reference: api/reference.md
          - Examples: api/examples.md
          - Error Handling: api/error-handling.md
    - Architecture:
          - System Overview: architecture/overview.md
          - Technology Stack: architecture/technology-stack.md
          - Design Decisions: architecture/design-decisions.md
          - Legacy Integration: architecture/legacy-integration.md
    - Operations:
          - Release & Distribution: operations/deployment.md
          - Documentation Deployment: operations/documentation-deployment.md
          - Monitoring: operations/monitoring.md
          - Maintenance: operations/maintenance.md

repo_url: https://gitlab.com/edu-boost/gitinspectorgui
edit_uri: -/edit/main/docs/

extra:
    social:
        - icon: fontawesome/brands/gitlab
          link: https://gitlab.com/edu-boost/gitinspectorgui
