site_name: GitInspectorGUI Developer Documentation
site_description: Developer documentation for GitInspectorGUI desktop application
site_url: https://edu-boost.gitlab.io/gitinspectorgui
# Note: Update URLs above when forking/moving this project

theme:
    name: material
    palette:
        - scheme: default
          primary: blue
          accent: blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: blue
          accent: blue
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    features:
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - search.highlight
        - search.share
        - content.code.copy
        - content.action.edit
        - content.tabs.link

plugins:
    - search:
          lang: en
    - mermaid2

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - admonition
    - pymdownx.details
    - pymdownx.mark
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.tilde
    - attr_list
    - md_in_html

nav:
    - Home: index.md
    - Technology Primer: technology-primer.md
    - Demo: https://edu-boost.gitlab.io/gitinspectorgui/demo/
    - Getting Started:
          - Prerequisites: getting-started/01-prerequisites.md
          - Installation: getting-started/02-installation.md
          - Quick Start: getting-started/03-quick-start.md
          - First Analysis: getting-started/04-first-analysis.md
          - CLI Guide: getting-started/cli-guide.md
    - Development:
          - Development Architecture: development/development-architecture.md
          - Development Workflow: development/development-workflow.md
          - Development vs Production: development/modes-comparison.md
          - Commands Reference: development/development-commands.md
          - Environment Setup: development/environment-setup.md
          - Package Management: development/package-management.md
          - Build Process: development/build-process.md
          - Troubleshooting: development/troubleshooting.md
          - Advanced:
                - Demo-Based Development: development/advanced/demo-based-development.md
                - Design System Integration: development/advanced/design-system-integration.md
    - AI Tools:
          - Overview: ai-tools/overview.md
          - Roo Code Development Guide: ai-tools/roo-code-guide.md
          - Cline Development Guide: ai-tools/cline-guide.md
    - API Reference:
          - HTTP API Reference: api/reference.md
          - Examples: api/examples.md
          - Error Handling: api/error-handling.md
    - Architecture:
          - System Overview: architecture/overview.md
          - Technology Stack: architecture/technology-stack.md
          - Design Background: architecture/design-background-info.md
          - Design Decisions: architecture/design-decisions.md
          - Legacy Integration: architecture/legacy-integration.md
    - Operations:
          - Release & Distribution: operations/deployment.md
          - Server Management: operations/server-management.md
          - Documentation Deployment: operations/documentation-deployment.md
          - Monitoring: operations/monitoring.md
          - Maintenance: operations/maintenance.md

repo_url: https://gitlab.com/edu-boost/gitinspectorgui
edit_uri: -/edit/main/docs/

extra:
    social:
        - icon: fontawesome/brands/gitlab
          link: https://gitlab.com/edu-boost/gitinspectorgui
