#!/bin/bash

# Script to switch between different GitLab CI/CD configurations

set -e

CI_CONFIG_FILE=".gitlab-ci.yml"
CI_PARTIALS_DIR=".ci"

show_help() {
    echo "GitLab CI/CD Configuration Switcher"
    echo "===================================="
    echo ""
    echo "Usage: $0 [OPTION]"
    echo ""
    echo "Options:"
    echo "  docs     Enable documentation-only CI/CD"
    echo "  apps     Enable full application build CI/CD"
    echo "  off      Disable all CI/CD pipelines"
    echo "  status   Show current CI/CD configuration"
    echo "  help     Show this help message"
}

show_status() {
    echo "Current GitLab CI/CD Status:"
    echo "============================"

    if [ -f "$CI_CONFIG_FILE" ]; then
        echo "✅ CI/CD is ENABLED"
        if grep -q "build:linux" "$CI_CONFIG_FILE"; then
            echo "🏗️  Type: Full application build pipeline"
        elif grep -q "pages:" "$CI_CONFIG_FILE"; then
            echo "📖 Type: Documentation-only pipeline"
        else
            echo "❓ Type: Unknown configuration"
        fi
        echo "📁 Active file: $CI_CONFIG_FILE (generated)"
    else
        echo "❌ CI/CD is DISABLED"
    fi

    echo ""
    echo "Available partial configurations in $CI_PARTIALS_DIR/:"
    ls -1 "$CI_PARTIALS_DIR" | sed 's/^/  - /'
}

generate_ci_config() {
    rm -f "$CI_CONFIG_FILE"
    echo "# Auto-generated by scripts/switch-ci.sh. DO NOT EDIT." > "$CI_CONFIG_FILE"
    for part in "$@"; do
        cat "$CI_PARTIALS_DIR/$part.yml" >> "$CI_CONFIG_FILE"
        echo "" >> "$CI_CONFIG_FILE"
    done
}

enable_docs_ci() {
    generate_ci_config "base" "docs"
    echo "✅ Documentation-only CI/CD enabled"
}

enable_apps_ci() {
    generate_ci_config "base" "app" "docs"
    echo "✅ Full application build CI/CD enabled"
}

disable_ci() {
    rm -f "$CI_CONFIG_FILE"
    echo "✅ CI/CD disabled"
}

# Main script logic
case "${1:-help}" in
    "docs")
        echo "🔄 Enabling documentation-only CI/CD..."
        enable_docs_ci
        ;;
    "apps")
        echo "🔄 Enabling full application build CI/CD..."
        enable_apps_ci
        ;;
    "off")
        echo "🔄 Disabling CI/CD..."
        disable_ci
        ;;
    "status")
        show_status
        ;;
    "help"|"-h"|"--help")
        show_help
        ;;
    *)
        echo "❌ Unknown option: $1"
        echo ""
        show_help
        exit 1
        ;;
esac
