use clap::{Arg, ArgAction, Command, ValueHint};

/// Create the command-line argument parser
pub fn create_parser() -> Command {
    Command::new("GitInspectorGUI")
        .version("0.1.0")
        .about("Modern git repository analysis tool")
        .arg(
            Arg::new("repositories")
                .help("Repository paths to analyze")
                .value_name("REPOSITORIES")
                .action(ArgAction::Append)
                .value_hint(ValueHint::DirPath)
        )
        .arg(
            Arg::new("depth")
                .long("depth")
                .help("Maximum directory depth to search for repositories")
                .value_name("DEPTH")
                .default_value("3")
                .value_parser(clap::value_parser!(u32))
        )
        .arg(
            Arg::new("n-files")
                .long("n-files")
                .help("Maximum number of files to analyze per repository")
                .value_name("N_FILES")
                .default_value("100")
                .value_parser(clap::value_parser!(u32))
        )
        .arg(
            Arg::new("include-files")
                .long("include-files")
                .help("File patterns to include in analysis")
                .value_name("PATTERNS")
                .action(ArgAction::Append)
        )
        .arg(
            Arg::new("exclude-files")
                .long("exclude-files")
                .help("File patterns to exclude from analysis")
                .value_name("PATTERNS")
                .action(ArgAction::Append)
        )
        .arg(
            Arg::new("exclude-authors")
                .long("exclude-authors")
                .help("Author patterns to exclude from analysis")
                .value_name("PATTERNS")
                .action(ArgAction::Append)
        )
        .arg(
            Arg::new("exclude-emails")
                .long("exclude-emails")
                .help("Email patterns to exclude from analysis")
                .value_name("PATTERNS")
                .action(ArgAction::Append)
        )
        .arg(
            Arg::new("copy-move")
                .long("copy-move")
                .help("Copy/move detection: 0=None, 1=Copy, 2=Move, 3=Both")
                .value_name("MODE")
                .default_value("0")
                .value_parser(["0", "1", "2", "3"])
        )
        .arg(
            Arg::new("scaled-percentages")
                .long("scaled-percentages")
                .help("Use scaled percentages in output")
                .action(ArgAction::SetTrue)
        )
        .arg(
            Arg::new("blame-exclusions")
                .long("blame-exclusions")
                .help("Enable blame exclusions")
                .action(ArgAction::SetTrue)
        )
        .arg(
            Arg::new("dynamic-blame-history")
                .long("dynamic-blame-history")
                .help("Enable dynamic blame history")
                .action(ArgAction::SetTrue)
        )
        .arg(
            Arg::new("dry-run")
                .long("dry-run")
                .help("Perform a dry run (preview only)")
                .action(ArgAction::SetTrue)
        )
        .arg(
            Arg::new("output-format")
                .long("output-format")
                .help("Output format")
                .value_name("FORMAT")
                .default_value("table")
                .value_parser(["json", "table"])
        )
}